SUBROUTINE isomat(sseiso,diso,c10,cbari1)



!>     ISOTROPIC MATRIX : ISOCHORIC SEF AND DERIVATIVES
use global
IMPLICIT NONE


DOUBLE PRECISION, INTENT(OUT)            :: sseiso
DOUBLE PRECISION, INTENT(OUT)            :: diso(5)
DOUBLE PRECISION, INTENT(IN)             :: c10
!DOUBLE PRECISION, INTENT(IN)             :: c01
DOUBLE PRECISION, INTENT(IN OUT)         :: cbari1
!DOUBLE PRECISION, INTENT(IN OUT)         :: cbari2


SSEISO=C10*(CBARI1-THREE)

!FIRST DERIVATIVE OF SSEISO IN ORDER TO I1
DISO(1)=C10
!FIRST DERIVATIVE OF SSEISO IN ORDER TO I2
DISO(2)=ZERO
!SECOND DERIVATIVE OF SSEISO IN ORDER TO I1
DISO(3)=ZERO
!SECOND DERIVATIVE OF SSEISO IN ORDER TO I2
DISO(4)=ZERO
!SECOND DERIVATIVE OF SSEISO IN ORDER TO I1 AND I2
DISO(5)=ZERO

RETURN
END SUBROUTINE isomat
